config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :sign_up_twos
  resources :sign_up_ones
  resources :sign_in_twos
  resources :sign_in_ones

end

app/models/sign_up_two.rb
class SignUpTwo < ActiveRecord::Base
end

app/controllers/sign_up_twos_controller.rb
class SignUpTwosController < ApplicationController
  before_action :set_sign_up_two, only: [:show, :edit, :update, :destroy]

  # GET /sign_up_twos
  # GET /sign_up_twos.json
  def index
    @sign_up_twos = SignUpTwo.all
  end

  # GET /sign_up_twos/1
  # GET /sign_up_twos/1.json
  def show
  end

  # GET /sign_up_twos/new
  def new
    @sign_up_two = SignUpTwo.new
  end

  # GET /sign_up_twos/1/edit
  def edit
  end

  # POST /sign_up_twos
  # POST /sign_up_twos.json
  def create
    @sign_up_two = SignUpTwo.new(sign_up_two_params)

    respond_to do |format|
      if @sign_up_two.save
        format.html { redirect_to @sign_up_two, notice: 'Sign up two was successfully created.' }
        format.json { render :show, status: :created, location: @sign_up_two }
      else
        format.html { render :new }
        format.json { render json: @sign_up_two.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sign_up_twos/1
  # PATCH/PUT /sign_up_twos/1.json
  def update
    respond_to do |format|
      if @sign_up_two.update(sign_up_two_params)
        format.html { redirect_to @sign_up_two, notice: 'Sign up two was successfully updated.' }
        format.json { render :show, status: :ok, location: @sign_up_two }
      else
        format.html { render :edit }
        format.json { render json: @sign_up_two.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sign_up_twos/1
  # DELETE /sign_up_twos/1.json
  def destroy
    @sign_up_two.destroy
    respond_to do |format|
      format.html { redirect_to sign_up_twos_url, notice: 'Sign up two was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sign_up_two
      @sign_up_two = SignUpTwo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sign_up_two_params
      params.require(:sign_up_two).permit(:firstname, :middlename, :lastname, :username, :PMDCno, :email, :phoneno, :cellno, :dateofbirth, :password, :confirmpassword, :speciality, :city, :institution, :officehourstart, :officehourend)
    end
end

app/helpers/sign_up_twos_helper.rb
module SignUpTwosHelper
end

app/views/sign_up_twos/_form.html.erb
<body style="background-color:grey;">

<div id="content">
  <img src="/SIGNUP.png" alt="appointment" height="200" width="200" align="right" align="top" border="10" style="text-align:right; vertical-align:top; border-color:#ff0000 #0000ff;";>
  <img src="/doctor.jpg" alt="appointment" height="200" width="200" align="right" align="top" border="10" style="text-align:right; vertical-align:top; border-color:#ff0000 #0000ff;";>
</div>

<h1>SignUp for doctors</h1>

<div style="background-color:black; color:white; padding:10px; font-weight:bold;" background="bgimage.jpg">
  
<%= form_for(@sign_up_two) do |f| %>
  <% if @sign_up_two.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sign_up_two.errors.count, "error") %> prohibited this sign_up_two from being saved:</h2>

      <ul>
      <% @sign_up_two.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :middlename %><br>
    <%= f.text_field :middlename %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :PMDCno %><br>
    <%= f.number_field :PMDCno %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phoneno %><br>
    <%= f.text_field :phoneno %>
  </div>
  <div class="field">
    <%= f.label :cellno %><br>
    <%= f.text_field :cellno %>
  </div>
  <div class="field">
    <%= f.label :dateofbirth %><br>
    <%= f.datetime_select :dateofbirth %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :confirmpassword %><br>
    <%= f.text_field :confirmpassword %>
  </div>
  <div class="field">
    <%= f.label :speciality %><br>
    <%= f.text_field :speciality %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :institution %><br>
    <%= f.text_field :institution %>
  </div>
  <div class="field">
    <%= f.label :officehourstart %><br>
    <%= f.time_select :officehourstart %>
  </div>
  <div class="field">
    <%= f.label :officehourend %><br>
    <%= f.time_select :officehourend %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

</div>

app/views/sign_up_twos/edit.html.erb
<h1>Editing Sign Up Two</h1>

<%= render 'form' %>

<%= link_to 'Show', @sign_up_two %> |
<%= link_to 'Back', sign_up_twos_path %>

app/views/sign_up_twos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sign Up Twos</h1>

<table border="5">
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Middlename</th>
      <th>Lastname</th>
      <th>Username</th>
      <th>Pmdcno</th>
      <th>Email</th>
      <th>Phoneno</th>
      <th>Cellno</th>
      <th>Dateofbirth</th>
      <th>Password</th>
      <th>Confirmpassword</th>
      <th>Speciality</th>
      <th>City</th>
      <th>Institution</th>
      <th>Officehourstart</th>
      <th>Officehourend</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sign_up_twos.each do |sign_up_two| %>
      <tr>
        <td><%= sign_up_two.firstname %></td>
        <td><%= sign_up_two.middlename %></td>
        <td><%= sign_up_two.lastname %></td>
        <td><%= sign_up_two.username %></td>
        <td><%= sign_up_two.PMDCno %></td>
        <td><%= sign_up_two.email %></td>
        <td><%= sign_up_two.phoneno %></td>
        <td><%= sign_up_two.cellno %></td>
        <td><%= sign_up_two.dateofbirth %></td>
        <td><%= sign_up_two.password %></td>
        <td><%= sign_up_two.confirmpassword %></td>
        <td><%= sign_up_two.speciality %></td>
        <td><%= sign_up_two.city %></td>
        <td><%= sign_up_two.institution %></td>
        <td><%= sign_up_two.officehourstart %></td>
        <td><%= sign_up_two.officehourend %></td>
        <td><%= link_to 'Show', sign_up_two %></td>
        <td><%= link_to 'Edit', edit_sign_up_two_path(sign_up_two) %></td>
        <td><%= link_to 'Destroy', sign_up_two, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sign up two', new_sign_up_two_path %>

app/views/sign_up_twos/new.html.erb
<h1>New Sign Up Two</h1>

<%= render 'form' %>

<%= link_to 'Back', sign_up_twos_path %>

app/views/sign_up_twos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @sign_up_two.firstname %>
</p>

<p>
  <strong>Middlename:</strong>
  <%= @sign_up_two.middlename %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @sign_up_two.lastname %>
</p>

<p>
  <strong>Username:</strong>
  <%= @sign_up_two.username %>
</p>

<p>
  <strong>Pmdcno:</strong>
  <%= @sign_up_two.PMDCno %>
</p>

<p>
  <strong>Email:</strong>
  <%= @sign_up_two.email %>
</p>

<p>
  <strong>Phoneno:</strong>
  <%= @sign_up_two.phoneno %>
</p>

<p>
  <strong>Cellno:</strong>
  <%= @sign_up_two.cellno %>
</p>

<p>
  <strong>Dateofbirth:</strong>
  <%= @sign_up_two.dateofbirth %>
</p>

<p>
  <strong>Password:</strong>
  <%= @sign_up_two.password %>
</p>

<p>
  <strong>Confirmpassword:</strong>
  <%= @sign_up_two.confirmpassword %>
</p>

<p>
  <strong>Speciality:</strong>
  <%= @sign_up_two.speciality %>
</p>

<p>
  <strong>City:</strong>
  <%= @sign_up_two.city %>
</p>

<p>
  <strong>Institution:</strong>
  <%= @sign_up_two.institution %>
</p>

<p>
  <strong>Officehourstart:</strong>
  <%= @sign_up_two.officehourstart %>
</p>

<p>
  <strong>Officehourend:</strong>
  <%= @sign_up_two.officehourend %>
</p>

<%= link_to 'Edit', edit_sign_up_two_path(@sign_up_two) %> |
<%= link_to 'Back', sign_up_twos_path %>