config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :sign_up_twos
  resources :sign_up_ones
  resources :sign_in_twos
  resources :sign_in_ones

end

app/models/sign_up_one.rb
class SignUpOne < ActiveRecord::Base
    
    E_regex=/\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/
    
    validates   :firstname,      :presence   =>  true
    
    validates   :lastname,       :presence   =>  true
    
    validates   :username,       :presence   =>  true
    
    validates   :city,           :presence   =>  true
    
    validates   :email,          :presence   =>  true
    validates   :email,          :format     =>  {:with => E_regex}
    
    validates   :password,              :presence   =>  true
    Pswrd   =   :password
    validates   :confirmpassword,       :presence   =>  true
    
    validate :validate_confirmpassword
    validate :validate_city
    
    validates   :password,              confirmation: true
    validates   :confirmpassword,       presence: true
    
    
    def validate_confirmpassword
        if (self.confirmpassword != self.password)
          errors.add(:password,         "password must equal confirmpassword")
          errors.add(:confirmpassword,  "password must equal confirmpassword")
        end
    end
    def validate_city
        if (self.city != ("lahore"||"karachi"||"islamabad"))
          errors.add(:city, "Enter a Valid city (eg: Lahore)")
        end
    end
end

app/controllers/sign_up_ones_controller.rb
class SignUpOnesController < ApplicationController
  before_action :set_sign_up_one, only: [:show, :edit, :update, :destroy]

  # GET /sign_up_ones
  # GET /sign_up_ones.json
  def index
    @sign_up_ones = SignUpOne.all
  end

  # GET /sign_up_ones/1
  # GET /sign_up_ones/1.json
  def show
  end

  # GET /sign_up_ones/new
  def new
    @sign_up_one = SignUpOne.new
  end

  # GET /sign_up_ones/1/edit
  def edit
  end

  # POST /sign_up_ones
  # POST /sign_up_ones.json
  def create
    @sign_up_one = SignUpOne.new(sign_up_one_params)

    respond_to do |format|
      if @sign_up_one.save
        format.html { redirect_to @sign_up_one, notice: 'Sign up one was successfully created.' }
        format.json { render :show, status: :created, location: @sign_up_one }
      else
        format.html { render :new }
        format.json { render json: @sign_up_one.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sign_up_ones/1
  # PATCH/PUT /sign_up_ones/1.json
  def update
    respond_to do |format|
      if @sign_up_one.update(sign_up_one_params)
        format.html { redirect_to @sign_up_one, notice: 'Sign up one was successfully updated.' }
        format.json { render :show, status: :ok, location: @sign_up_one }
      else
        format.html { render :edit }
        format.json { render json: @sign_up_one.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sign_up_ones/1
  # DELETE /sign_up_ones/1.json
  def destroy
    @sign_up_one.destroy
    respond_to do |format|
      format.html { redirect_to sign_up_ones_url, notice: 'Sign up one was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sign_up_one
      @sign_up_one = SignUpOne.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sign_up_one_params
      params.require(:sign_up_one).permit(:firstname, :middlename, :lastname, :username, :email, :phoneno, :cellno, :city, :dateofbirth, :password, :confirmpassword)
    end
end

app/helpers/sign_up_ones_helper.rb
module SignUpOnesHelper
end

app/views/sign_up_ones/_form.html.erb
<body style="background-color:lightyellow;">

<div id="content">
  <img src="/SIGNUP.png" alt="appointment" height="200" width="200" align="right" align="top" border="10" style="text-align:right; vertical-align:top; border-color:#ff0000 #0000ff;";>
</div>

<h1>SignUp for patients</h1>

<div style="background-color:black; color:white; padding:10px; font-weight:bold;" background="bgimage.jpg">

<%= form_for(@sign_up_one) do |f| %>
  <% if @sign_up_one.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sign_up_one.errors.count, "error") %> prohibited this sign_up_one from being saved:</h2>

      <ul>
      <% @sign_up_one.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :middlename %><br>
    <%= f.text_field :middlename %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phoneno %><br>
    <%= f.text_field :phoneno %>
  </div>
  <div class="field">
    <%= f.label :cellno %><br>
    <%= f.text_field :cellno %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :dateofbirth %><br>
    <%= f.datetime_select :dateofbirth %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :confirmpassword %><br>
    <%= f.text_field :confirmpassword %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

</div>

app/views/sign_up_ones/edit.html.erb
<h1>Editing Sign Up One</h1>

<%= render 'form' %>

<%= link_to 'Show', @sign_up_one %> |
<%= link_to 'Back', sign_up_ones_path %>

app/views/sign_up_ones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sign Up Ones</h1>

<table border="5">
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Middlename</th>
      <th>Lastname</th>
      <th>Username</th>
      <th>Email</th>
      <th>Phoneno</th>
      <th>Cellno</th>
      <th>City</th>
      <th>Dateofbirth</th>
      <th>Password</th>
      <th>Confirmpassword</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sign_up_ones.each do |sign_up_one| %>
      <tr>
        <td><%= sign_up_one.firstname %></td>
        <td><%= sign_up_one.middlename %></td>
        <td><%= sign_up_one.lastname %></td>
        <td><%= sign_up_one.username %></td>
        <td><%= sign_up_one.email %></td>
        <td><%= sign_up_one.phoneno %></td>
        <td><%= sign_up_one.cellno %></td>
        <td><%= sign_up_one.city %></td>
        <td><%= sign_up_one.dateofbirth %></td>
        <td><%= sign_up_one.password %></td>
        <td><%= sign_up_one.confirmpassword %></td>
        <td><%= link_to 'Show', sign_up_one %></td>
        <td><%= link_to 'Edit', edit_sign_up_one_path(sign_up_one) %></td>
        <td><%= link_to 'Destroy', sign_up_one, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sign up one', new_sign_up_one_path %>

app/views/sign_up_ones/new.html.erb
<h1>New Sign Up One</h1>

<%= render 'form' %>

<%= link_to 'Back', sign_up_ones_path %>

app/views/sign_up_ones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @sign_up_one.firstname %>
</p>

<p>
  <strong>Middlename:</strong>
  <%= @sign_up_one.middlename %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @sign_up_one.lastname %>
</p>

<p>
  <strong>Username:</strong>
  <%= @sign_up_one.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @sign_up_one.email %>
</p>

<p>
  <strong>Phoneno:</strong>
  <%= @sign_up_one.phoneno %>
</p>

<p>
  <strong>Cellno:</strong>
  <%= @sign_up_one.cellno %>
</p>

<p>
  <strong>City:</strong>
  <%= @sign_up_one.city %>
</p>

<p>
  <strong>Dateofbirth:</strong>
  <%= @sign_up_one.dateofbirth %>
</p>

<p>
  <strong>Password:</strong>
  <%= @sign_up_one.password %>
</p>

<p>
  <strong>Confirmpassword:</strong>
  <%= @sign_up_one.confirmpassword %>
</p>

<%= link_to 'Edit', edit_sign_up_one_path(@sign_up_one) %> |
<%= link_to 'Back', sign_up_ones_path %>