config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :sign_up_twos
  resources :sign_up_ones
  resources :sign_in_twos
  resources :sign_in_ones

end

app/models/sign_in_two.rb
class SignInTwo < ActiveRecord::Base
end

app/controllers/sign_in_twos_controller.rb
class SignInTwosController < ApplicationController
  before_action :set_sign_in_two, only: [:show, :edit, :update, :destroy]

  # GET /sign_in_twos
  # GET /sign_in_twos.json
  def index
    @sign_in_twos = SignInTwo.all
  end

  # GET /sign_in_twos/1
  # GET /sign_in_twos/1.json
  def show
  end

  # GET /sign_in_twos/new
  def new
    @sign_in_two = SignInTwo.new
  end

  # GET /sign_in_twos/1/edit
  def edit
  end

  # POST /sign_in_twos
  # POST /sign_in_twos.json
  def create
    @sign_in_two = SignInTwo.new(sign_in_two_params)

    respond_to do |format|
      if @sign_in_two.save
        format.html { redirect_to @sign_in_two, notice: 'Sign in two was successfully created.' }
        format.json { render :show, status: :created, location: @sign_in_two }
      else
        format.html { render :new }
        format.json { render json: @sign_in_two.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sign_in_twos/1
  # PATCH/PUT /sign_in_twos/1.json
  def update
    respond_to do |format|
      if @sign_in_two.update(sign_in_two_params)
        format.html { redirect_to @sign_in_two, notice: 'Sign in two was successfully updated.' }
        format.json { render :show, status: :ok, location: @sign_in_two }
      else
        format.html { render :edit }
        format.json { render json: @sign_in_two.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sign_in_twos/1
  # DELETE /sign_in_twos/1.json
  def destroy
    @sign_in_two.destroy
    respond_to do |format|
      format.html { redirect_to sign_in_twos_url, notice: 'Sign in two was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sign_in_two
      @sign_in_two = SignInTwo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sign_in_two_params
      params.require(:sign_in_two).permit(:name, :password, :doctorID)
    end
end

app/helpers/sign_in_twos_helper.rb
module SignInTwosHelper
end

app/views/sign_in_twos/_form.html.erb
<body style="background-color:lightgreen;">
<div id="content">
  <img src="/LOGIN.png" alt="appointment" height="200" width="200" align="right" align="top" border="10" style="text-align:right; vertical-align:top; border-color:#ff0000 #0000ff;";>
  <img src="/doctor.jpg" alt="appointment" height="200" width="200" align="right" align="top" border="10" style="text-align:right; vertical-align:top; border-color:#ff0000 #0000ff;";>
</div>
<h1>SignIn for doctors</h1>

<div style="background-color:black; color:white; padding:10px; font-weight:bold;" background="bgimage.jpg">
<%= form_for(@sign_in_two) do |f| %>
  <% if @sign_in_two.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sign_in_two.errors.count, "error") %> prohibited this sign_in_two from being saved:</h2>

      <ul>
      <% @sign_in_two.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :doctorID %><br>
    <%= f.number_field :doctorID %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/sign_in_twos/edit.html.erb
<h1>Editing Sign In Two</h1>

<%= render 'form' %>

<%= link_to 'Show', @sign_in_two %> |
<%= link_to 'Back', sign_in_twos_path %>

app/views/sign_in_twos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sign In Twos</h1>

<table border="5">
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th>Doctorid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sign_in_twos.each do |sign_in_two| %>
      <tr>
        <td><%= sign_in_two.name %></td>
        <td><%= sign_in_two.password %></td>
        <td><%= sign_in_two.doctorID %></td>
        <td><%= link_to 'Show', sign_in_two %></td>
        <td><%= link_to 'Edit', edit_sign_in_two_path(sign_in_two) %></td>
        <td><%= link_to 'Destroy', sign_in_two, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sign in two', new_sign_in_two_path %>

app/views/sign_in_twos/new.html.erb
<h1>New Sign In Two</h1>

<%= render 'form' %>

<%= link_to 'Back', sign_in_twos_path %>

app/views/sign_in_twos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sign_in_two.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @sign_in_two.password %>
</p>

<p>
  <strong>Doctorid:</strong>
  <%= @sign_in_two.doctorID %>
</p>

<%= link_to 'Edit', edit_sign_in_two_path(@sign_in_two) %> |
<%= link_to 'Back', sign_in_twos_path %>