config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :sign_up_twos
  resources :sign_up_ones
  resources :sign_in_twos
  resources :sign_in_ones

end

app/models/sign_in_one.rb
class SignInOne < ActiveRecord::Base
    validates   :name,      :presence   =>  true
    validates   :password,  :presence   =>  true
    validates   :password,  uniqueness: { case_sensitive: true }
    
    def self.search(search)
        where("name LIKE ?", "%#{search}%") 
    end
end

app/controllers/sign_in_ones_controller.rb
class SignInOnesController < ApplicationController
  before_action :set_sign_in_one, only: [:show, :edit, :update, :destroy]

  # GET /sign_in_ones
  # GET /sign_in_ones.json
  def index
    @sign_in_ones = SignInOne.all
    
    if params[:search]
      @sign_in_ones = SignInOne.search(params[:search]).order("created_at DESC")
    else
      @sign_in_ones = SignInOne.all.order('created_at DESC')
    end
  end

  # GET /sign_in_ones/1
  # GET /sign_in_ones/1.json
  def show
  end

  # GET /sign_in_ones/new
  def new
    @sign_in_one = SignInOne.new
  end

  # GET /sign_in_ones/1/edit
  def edit
  end

  # POST /sign_in_ones
  # POST /sign_in_ones.json
  def create
    @sign_in_one = SignInOne.new(sign_in_one_params)

    respond_to do |format|
      if @sign_in_one.save
        format.html { redirect_to @sign_in_one, notice: 'Sign in one was successfully created.' }
        format.json { render :show, status: :created, location: @sign_in_one }
      else
        format.html { render :new }
        format.json { render json: @sign_in_one.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sign_in_ones/1
  # PATCH/PUT /sign_in_ones/1.json
  def update
    respond_to do |format|
      if @sign_in_one.update(sign_in_one_params)
        format.html { redirect_to @sign_in_one, notice: 'Sign in one was successfully updated.' }
        format.json { render :show, status: :ok, location: @sign_in_one }
      else
        format.html { render :edit }
        format.json { render json: @sign_in_one.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sign_in_ones/1
  # DELETE /sign_in_ones/1.json
  def destroy
    @sign_in_one.destroy
    respond_to do |format|
      format.html { redirect_to sign_in_ones_url, notice: 'Sign in one was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sign_in_one
      @sign_in_one = SignInOne.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sign_in_one_params
      params.require(:sign_in_one).permit(:name, :password)
    end
end

app/helpers/sign_in_ones_helper.rb
module SignInOnesHelper
end

app/views/sign_in_ones/_form.html.erb
<body style="background-color:lightblue;">

<div id="content">
  <img src="/LOGIN.png" alt="appointment" height="200" width="200" align="right" align="top" border="10" style="text-align:right; vertical-align:top; border-color:#ff0000 #0000ff;";>
</div>

<h1>SignIn for patients</h1>

<div style="background-color:black; color:white; padding:10px; font-weight:bold;" background="bgimage.jpg">

<%= form_for(@sign_in_one) do |f| %>
  <% if @sign_in_one.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sign_in_one.errors.count, "error") %> prohibited this sign_in_one from being saved:</h2>

      <ul>
      <% @sign_in_one.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  
  <%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
  <%= submit_tag "Search" %>
  
 
  
<% end %>

</div>

app/views/sign_in_ones/edit.html.erb
<h1>Editing Sign In One</h1>

<%= render 'form' %>

<%= link_to 'Show', @sign_in_one %> |
<%= link_to 'Back', sign_in_ones_path %>

app/views/sign_in_ones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sign In Ones</h1>

<table  border="5">
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sign_in_ones.each do |sign_in_one| %>
      <tr>
        <td><%= sign_in_one.name %></td>
        <td><%= sign_in_one.password %></td>
        <td><%= link_to 'Show', sign_in_one %></td>
        <td><%= link_to 'Edit', edit_sign_in_one_path(sign_in_one) %></td>
        <td><%= link_to 'Destroy', sign_in_one, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sign in one', new_sign_in_one_path %>

app/views/sign_in_ones/new.html.erb
<h1>New Sign In One</h1>

<%= render 'form' %>

<%= link_to 'Back', sign_in_ones_path %>

app/views/sign_in_ones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sign_in_one.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @sign_in_one.password %>
</p>

<%= link_to 'Edit', edit_sign_in_one_path(@sign_in_one) %> |
<%= link_to 'Back', sign_in_ones_path %>